name = "pprint"
version = "1.0.5"
description = "Pretty print values with style!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "MystPi", repo = "pprint" }

internal_modules = ["pprint/decoder"]

[dependencies]
gleam_stdlib = ">= 0.50.0 and < 2.0.0"
glam = "~> 2.0"

[dev-dependencies]
gleeunit = "~> 1.0"
birdie = "~> 1.0"
